import type { CitySummary } from '../domain/types';

export const sampleCities: CitySummary[] = [
  {
    id: 2867714,
    name: 'München',
    asciiName: 'Munich',
    aliases: ['Muenchen', 'Munich', '慕尼黑'],
    zhName: '慕尼黑',
    countryCode: 'DE',
    continentCode: 'EU',
    admin1: '02',
    lat: 48.13743,
    lon: 11.57549,
    population: 1_260_391,
  },
  {
    id: 3448439,
    name: 'São Paulo',
    asciiName: 'Sao Paulo',
    aliases: ['Sampa'],
    zhName: '圣保罗',
    countryCode: 'BR',
    continentCode: 'SA',
    admin1: '27',
    lat: -23.5475,
    lon: -46.63611,
    population: 12_400_232,
  },
  {
    id: 4250542,
    name: 'Springfield',
    asciiName: 'Springfield',
    aliases: [],
    countryCode: 'US',
    continentCode: 'NA',
    admin1: 'IL',
    lat: 39.80172,
    lon: -89.64371,
    population: 114_394,
  },
  {
    id: 4409896,
    name: 'Springfield',
    asciiName: 'Springfield',
    aliases: [],
    countryCode: 'US',
    continentCode: 'NA',
    admin1: 'MO',
    lat: 37.21533,
    lon: -93.29824,
    population: 169_176,
  },
  {
    id: 9_000_001,
    name: 'Dateline East',
    asciiName: 'Dateline East',
    aliases: [],
    countryCode: 'FJ',
    continentCode: 'OC',
    lat: 0,
    lon: 179.8,
  },
  {
    id: 9_000_002,
    name: 'Dateline West',
    asciiName: 'Dateline West',
    aliases: [],
    countryCode: 'FJ',
    continentCode: 'OC',
    lat: 0,
    lon: -179.95,
  },
];
